SELECT * FROM EMP_USERS_DETAILS WHERE EMP_ID=240122
DELETE FROM EMP_USERS_DETAILS WHERE EMP_ID=240122

INSERT INTO EMP_USERS_DETAILS(
EMP_ID,TXT_USERNAME,EMP_STATUS,EMP_MODE,NUM_SICK_LV,NUM_CASUAL_LV,NUM_WORK_FROM_HOME,SYS_DATE_TIME )
VALUES(
240122,'WASIM','ACTIVE','EMPLOYEE',6.0,12.0,30.0,GETDATE())