CREATE TABLE EMP_USERS_DETAILS(
ID BIGINT IDENTITY (1,1),
EMP_ID BIGINT PRIMARY KEY,
TXT_USERNAME VARCHAR(200) UNIQUE NOT NULL,
EMP_STATUS VARCHAR (50),
EMP_MODE VARCHAR (50),
NUM_SICK_LV NUMERIC (18,2) DEFAULT 0 NOT NULL,
NUM_CASUAL_LV NUMERIC (18,2) DEFAULT 0 NOT NULL,
NUM_WORK_FROM_HOME NUMERIC (18,2) DEFAULT 0 NOT NULL,
SYS_DATE_TIME DATETIME
)

CREATE SEQUENCE [dbo].[seq_gen_emp_id] 
 AS [bigint]
 START WITH 1200
 INCREMENT BY 1
 MINVALUE 1
 MAXVALUE 9223372036854775807
 CYCLE 
 CACHE  30 
GO


CREATE TABLE EMP_LEAVE_RECORDS
(
ID BIGINT IDENTITY (1,1), 
EMP_ID BIGINT NOT NULL, 
LEAVE_ID BIGINT PRIMARY KEY, 
LEAVE_TYPE VARCHAR(50), 
SHIFT_TYPE VARCHAR(50),
LV_STARTDATE DATE,
LV_ENDDATE DATE,
HOLIDAY NUMERIC (18,1) NOT NULL DEFAULT 0,
WORK_FROM_HOME NUMERIC (18,1) NOT NULL DEFAULT 0,
EXTRA_WORK NUMERIC (18,1) NOT NULL DEFAULT 0,
LEAVE_COMMENT_REMARKS VARCHAR (500),
SYS_DATE_TIME DATETIME
)

CREATE SEQUENCE SEQ_GEN_LEAVE_ID
AS BIGINT
START WITH 1000
MINVALUE 1
NO MAXVALUE
NO CYCLE


CREATE TABLE [dbo].[LOG_LOGINANDOUT](
	[REF_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMP_ID] [bigint] NOT NULL,
	[TXT_EMP_USERNAME] [varchar](100) NULL,
	[LOGIN_TIME] [datetime] NULL,
	[LOGOUT_TIME] [datetime] NULL,
	[EMP_STATUS] [varchar](50) NULL,
	[SYS_DATE_TIME] [datetime] NULL,
) 


CREATE DATABASE EMP_LV_MANAGE